name: Continuous Benchmark

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # Run every 4 hours
    - cron: "0 */4 * * *"

jobs:
  runTenantsBenchmark:
    runs-on: ubuntu-latest
    needs: runBenchmark
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Benches
        id: benches
        run: |
            export HCLOUD_TOKEN=${{ secrets.HCLOUD_TOKEN }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            bash -x tools/setup_ci.sh

            set +e

            # Benchmark filtered search by tenants with mem limitation

            export ENGINE_NAME="qdrant-all-on-disk-scalar-q"
            export DATASETS="random-768-100-tenants"
            export CONTAINER_MEM_LIMIT=150mb

            # Benchmark the dev branch:
            export QDRANT_VERSION=ghcr/dev
            timeout 30m bash -x tools/run_ci.sh

            # Benchmark the master branch:
            export QDRANT_VERSION=docker/master
            timeout 30m bash -x tools/run_ci.sh

            set -e
      - name: Fail job if any of the benches failed
        if: steps.benches.outputs.failed == 'error' || steps.benches.outputs.failed == 'timeout'
        run: exit 1